In [1]:
import os
import pandas as pd
from sqlalchemy import create_engine

DB_URL = os.environ.get("DB_URL", "postgresql://jhu:jhu123@postgres:5432/jhu")
engine = create_engine(DB_URL)

In [2]:
# sets up CSV to be loaded
CDC_PLACES_CSV = "/home/jhu/cdc_places_mhlth_sleep.csv"
DATA_VALUE_TYPE = "Crude prevalence"  # switch to "Age-adjusted prevalence" here if the team decides otherwise

raw = pd.read_csv(CDC_PLACES_CSV)
cdc = raw[raw["Data_Value_Type"] == DATA_VALUE_TYPE].copy()

# fixes column names
cdc = cdc.rename(columns={
    "LocationID": "county_fips",
    "LocationName": "county_name",
    "StateAbbr": "state_abbr",
    "Year": "year",
    "MeasureId": "measure_id",
    "Data_Value": "data_value",
    "Data_Value_Type": "data_value_type",
})

# quick clean of data
cdc["county_fips"] = cdc["county_fips"].astype(str).str.zfill(5)
cdc["data_value"] = pd.to_numeric(cdc["data_value"], errors="coerce")
cdc = cdc.dropna(subset=["data_value"])

cdc_places_raw = cdc[["county_fips", "county_name", "state_abbr", "year", "measure_id", "data_value", "data_value_type"]]

print(f"{len(cdc_places_raw)} rows, {cdc_places_raw['county_fips'].nunique()} counties, years {sorted(cdc_places_raw['year'].unique())}")
cdc_places_raw.head()

6101 rows, 3144 counties, years [2022, 2023]

,county_fips,county_name,state_abbr,year,measure_id,data_value,data_value_type
3,02195,Petersburg,AK,2022,SLEEP,32.5,Crude prevalence
5,05117,Prairie,AR,2023,MHLTH,18.0,Crude prevalence
7,05053,Grant,AR,2022,SLEEP,38.1,Crude prevalence
8,01049,DeKalb,AL,2022,SLEEP,40.3,Crude prevalence
9,01129,Washington,AL,2023,MHLTH,17.7,Crude prevalence

In [3]:
# Stage data to Postgres
cdc_places_raw.to_sql("cdc_places_raw", engine, if_exists="replace", index=False)
print(f"Staged {len(cdc_places_raw)} rows into cdc_places_raw")

Staged 6101 rows into cdc_places_raw

In [4]:
pd.read_sql("""
    SELECT measure_id, COUNT(*) AS rows, COUNT(DISTINCT county_fips) AS counties, MIN(year), MAX(year)
    FROM cdc_places_raw
    GROUP BY measure_id
    ORDER BY measure_id;
""", engine)

  measure_id  rows  counties   min   max
0      MHLTH  2957      2957  2023  2023
1      SLEEP  3144      3144  2022  2022

In [5]:
# preview only — Dim_County itself gets written in 04_transform_load.ipynb
dim_county_preview = cdc_places_raw[["county_fips", "county_name", "state_abbr"]].drop_duplicates().sort_values("county_fips")
print(f"{len(dim_county_preview)} distinct counties")
dim_county_preview.head()

3144 distinct counties

    county_fips county_name state_abbr
217       00059         NaN         US
143       01001     Autauga         AL
230       01003     Baldwin         AL
209       01005     Barbour         AL
218       01007        Bibb         AL